selected_scheme scheme-custom
TEXDIR /texlive/
TEXMFLOCAL /texlive/texmf-local
TEXMFSYSCONFIG /texlive/texmf-config
TEXMFSYSVAR /texlive/texmf-var
option_doc 0
option_src 0
binary_x86_64-linux 1
collection-basic 0
collection-latex 1
collection-latexrecommended 1
collection-luatex 1
collection-langgerman 1